### ISSUE TITLE
npm v3 flattened dependency resolutions

### ISSUE THREAD

**Issue by kahboom** [patternfly/patternfly-demo-app#10]
Hey, thanks for providing this demo app; it's been really useful for integrating PatternFly into an existing project. I have some feedback:
1. As of npm 3 all dependencies are flattened, not hierarchical. See [here](https://docs.npmjs.com/how-npm-works/npm3). That basically means that the paths provided for subdependencies, such as [here](https://github.com/patternfly/patternfly-demo-app/blob/master/src/js/main.js#L11) will no longer work if you are using npm 3.
2. There isn't really a need to install webpack globally, as npm can use the executable binary that is provided within the `node_modules` directory. The only downside to that would be that you couldn't run `webpack` from the terminal for specific things, you'd need to execute the `webpack` command via npm scripts, but it's still a much safer practice and less headache-y.

I'd be happy to assist with these changes if you're currently accepting PRs- unless it's preferable to leave things as is. Either way, let me know. :)

**Comment by andresgalante** [comment]
Hi @kahboom thanks for your comment, it'd be great if you can send a PR
cc @priley86

**Comment by priley86** [comment]
@kahboom @andresgalante We are still in npm2 land and had just attempted running Webpack with Patternfly (as you can see!). Would happily accept a PR for an npm3 update!

+1 for removing webpack global install. I followed some other guides on this, but am happy to reference it from `node_modules`. Please just also update the README. 😄 

Would also be happy to hear any more challenges/successes you have with Webpack. I find myself returning to gulp and anxiously awaiting HTTP2/HTML Import standards, but I'm interested in how the Webpack story plays out. 😉 

P.S. Awesome devs like you are always welcome in Patternfly, and we can't thank you enough!

**Comment by kahboom** [comment]
@priley86 - Thanks, I appreciate the help and would be more than happy to contribute wherever I can. :) I'll be sure to update the README in my PR, which I'll hopefully get around to this/next week. The only issue I can see is that right now, for dev purposes, I'm referencing the CSS from a CDN, as I couldn't get the `patternfly-sass` GitHub repo properly installed with npm (and being version or tag aware). Going to try a few things and will get back to you.

**Comment by priley86** [comment]
@kahboom sounds good. I noticed the same issue with `patternfly-sass`, hopefully we can get this one in npm soon.
