### ISSUE TITLE
Paths on less

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-demo-app#2]
@priley86 I am opening this issue as a reminder.

Can we improve the path of the less imports? Also we should not import patternfly and patternfly-additions. There is a reason why we separate them. IE9 only reads 4095 CSS rules, in order to support Ie9 we had to separate the css into 2 files.

Lets talk about it on Tuesday 😄

**Comment by priley86** [comment]
@andresgalante yes of course - I forgot about this with the IE9 restriction. We should be able to do this.

Will make a PR after we discuss.
